camera0: "./videos/left_stream.avi"
camera1: "./videos/right_stream.avi"
frame_width: 1280
frame_height: 720
mono_calibration_frames: 5
stereo_calibration_frames: 5
view_resize: 1
checkerboard_box_size_scale : 3.19
checkerboard_rows: 4
checkerboard_columns: 7
cooldown: 3
